apiVersion: apps/v1
kind: Deployment
metadata:
  name: paiement-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: paiement-service
  template:
    metadata:
      labels:
        app: paiement-service
    spec:
      containers:
        - name: paiement-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-service:8888
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://discovery-service:8761/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-paiement-service:5432/paiementdb
            - name: SPRING_DATASOURCE_DRIVER
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: paiement_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: paiement_pass
